#need a workflow and then need a trigger
name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13.2
        uses: actions/setup-python@v3
        with:
          python-version: "3.13.2"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest flask
      - uses: actions/checkout@v3
      - run: pytest
